name: check if brash is formatted correctly

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout pr branch
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v2

      - name: install dependencies
        run: npm ci

      - name: check formatting
        run: npm run lint-check